"""Docker Compose操作"""

import os
import subprocess
from pathlib import Path

from ruamel.yaml import YAML

from treemux.models import ComposeResult, TreemuxConfig

OVERRIDE_FILE = "docker-compose.override.treemux.yml"


def generate_override_content(config: TreemuxConfig) -> dict:
    """オーバーライドファイルの内容を生成

    Args:
        config: treemux設定

    Returns:
        オーバーライドYAMLの内容
    """
    services: dict[str, dict] = {}

    for service_name, svc in config.services.items():
        # ハイフンは環境変数名に使用できないのでアンダースコアに変換
        env_name = service_name.upper().replace("-", "_")
        env_var = f"TREEMUX_{env_name}_PORT"
        default_port = svc.base_host_port
        services[service_name] = {
            "ports": [f"${{{env_var}:-{default_port}}}:{svc.container_port}"]
        }

    return {
        "services": services,
        "networks": {
            "default": {
                "name": "treemux-${TREEMUX_PROJECT_NAME:-default}",
            }
        },
    }


def write_override_file(project_root: Path, config: TreemuxConfig) -> Path:
    """オーバーライドファイルを書き出し

    Args:
        project_root: プロジェクトルートパス
        config: treemux設定

    Returns:
        書き出したファイルパス
    """
    content = generate_override_content(config)
    override_path = project_root / OVERRIDE_FILE

    yaml = YAML()
    yaml.default_flow_style = False

    with override_path.open("w", encoding="utf-8") as f:
        f.write("# Generated by treemux - DO NOT EDIT\n")
        yaml.dump(content, f)

    return override_path


def build_env_vars(
    project_name: str,
    ports: dict[str, int],
) -> dict[str, str]:
    """docker compose用の環境変数を構築

    Args:
        project_name: プロジェクト名
        ports: サービス名→ポート番号のマッピング

    Returns:
        環境変数の辞書
    """
    env_vars = {"TREEMUX_PROJECT_NAME": project_name}
    for service_name, port in ports.items():
        env_name = service_name.upper().replace("-", "_")
        env_vars[f"TREEMUX_{env_name}_PORT"] = str(port)
    return env_vars


def compose_up(
    project_root: Path,
    project_name: str,
    env_vars: dict[str, str],
    compose_file: str = "docker-compose.yml",
    detach: bool = True,
) -> ComposeResult:
    """docker compose up を実行

    Args:
        project_root: プロジェクトルートパス
        project_name: プロジェクト名
        env_vars: 環境変数
        compose_file: docker-compose.ymlのパス
        detach: デタッチモードで実行するか

    Returns:
        実行結果
    """
    cmd = [
        "docker",
        "compose",
        "--project-name",
        project_name,
        "-f",
        compose_file,
        "-f",
        OVERRIDE_FILE,
        "up",
    ]
    if detach:
        cmd.append("-d")

    merged_env = {**os.environ, **env_vars}
    result = subprocess.run(
        cmd,
        cwd=project_root,
        env=merged_env,
        capture_output=True,
        text=True,
    )

    return ComposeResult(
        success=result.returncode == 0,
        return_code=result.returncode,
        stdout=result.stdout,
        stderr=result.stderr,
        command=cmd,
    )


def compose_down(
    project_root: Path,
    project_name: str,
    compose_file: str = "docker-compose.yml",
    volumes: bool = False,
) -> ComposeResult:
    """docker compose down を実行

    Args:
        project_root: プロジェクトルートパス
        project_name: プロジェクト名
        compose_file: docker-compose.ymlのパス
        volumes: ボリュームも削除するか

    Returns:
        実行結果
    """
    cmd = [
        "docker",
        "compose",
        "--project-name",
        project_name,
        "-f",
        compose_file,
        "-f",
        OVERRIDE_FILE,
        "down",
    ]
    if volumes:
        cmd.append("-v")

    result = subprocess.run(
        cmd,
        cwd=project_root,
        capture_output=True,
        text=True,
    )

    return ComposeResult(
        success=result.returncode == 0,
        return_code=result.returncode,
        stdout=result.stdout,
        stderr=result.stderr,
        command=cmd,
    )


def compose_ps(
    project_root: Path,
    project_name: str,
    compose_file: str = "docker-compose.yml",
) -> ComposeResult:
    """docker compose ps を実行

    Args:
        project_root: プロジェクトルートパス
        project_name: プロジェクト名
        compose_file: docker-compose.ymlのパス

    Returns:
        実行結果
    """
    cmd = [
        "docker",
        "compose",
        "--project-name",
        project_name,
        "-f",
        compose_file,
        "-f",
        OVERRIDE_FILE,
        "ps",
        "--format",
        "json",
    ]

    result = subprocess.run(
        cmd,
        cwd=project_root,
        capture_output=True,
        text=True,
    )

    return ComposeResult(
        success=result.returncode == 0,
        return_code=result.returncode,
        stdout=result.stdout,
        stderr=result.stderr,
        command=cmd,
    )


def check_docker_compose_available() -> bool:
    """docker composeが利用可能か確認

    Returns:
        利用可能ならTrue
    """
    try:
        result = subprocess.run(
            ["docker", "compose", "version"],
            capture_output=True,
            text=True,
        )
        return result.returncode == 0
    except FileNotFoundError:
        return False


def get_override_file_path(project_root: Path) -> Path:
    """オーバーライドファイルのパスを取得"""
    return project_root / OVERRIDE_FILE


def override_file_exists(project_root: Path) -> bool:
    """オーバーライドファイルが存在するか確認"""
    return get_override_file_path(project_root).exists()
