"""Unit tests for treemux.compose."""

from pathlib import Path
from unittest.mock import MagicMock, patch

from treemux.compose import (
    OVERRIDE_FILE,
    build_env_vars,
    check_docker_compose_available,
    compose_down,
    compose_ps,
    compose_up,
    generate_override_content,
    get_override_file_path,
    override_file_exists,
    write_override_file,
)
from treemux.models import ServiceConfig, TreemuxConfig


class TestGenerateOverrideContent:
    """Tests for generate_override_content function."""

    def test_structure(self, sample_treemux_config: TreemuxConfig):
        """正しいdict構造を生成する"""
        content = generate_override_content(sample_treemux_config)

        assert "services" in content
        assert "networks" in content
        assert "default" in content["networks"]

    def test_port_format(self, sample_treemux_config: TreemuxConfig):
        """正しいポート変数フォーマットを生成する"""
        content = generate_override_content(sample_treemux_config)

        web_ports = content["services"]["web"]["ports"]
        assert len(web_ports) == 1
        assert "${TREEMUX_WEB_PORT:-8000}:3000" in web_ports[0]

        api_ports = content["services"]["api"]["ports"]
        assert "${TREEMUX_API_PORT:-8100}:5000" in api_ports[0]

    def test_network_name(self, sample_treemux_config: TreemuxConfig):
        """変数付きのネットワーク名を生成する"""
        content = generate_override_content(sample_treemux_config)

        network = content["networks"]["default"]
        assert network["name"] == "treemux-${TREEMUX_PROJECT_NAME:-default}"

    def test_empty_services(self):
        """空のservicesを処理する"""
        config = TreemuxConfig(project_name="test", services={})
        content = generate_override_content(config)

        assert content["services"] == {}

    def test_uppercase_service_name_in_env_var(self):
        """サービス名は環境変数で大文字化され、ハイフンはアンダースコアに変換される"""
        config = TreemuxConfig(
            project_name="test",
            services={
                "my-service": ServiceConfig(container_port=80, base_host_port=8080),
            },
        )
        content = generate_override_content(config)

        ports = content["services"]["my-service"]["ports"]
        assert "TREEMUX_MY_SERVICE_PORT" in ports[0]


class TestWriteOverrideFile:
    """Tests for write_override_file function."""

    def test_creates_file(
        self, project_root: Path, sample_treemux_config: TreemuxConfig
    ):
        """オーバーライドファイルを作成する"""
        result = write_override_file(project_root, sample_treemux_config)

        assert result.exists()
        assert result.name == OVERRIDE_FILE

    def test_file_has_header(
        self, project_root: Path, sample_treemux_config: TreemuxConfig
    ):
        """'DO NOT EDIT'ヘッダーを含む"""
        write_override_file(project_root, sample_treemux_config)

        override_path = project_root / OVERRIDE_FILE
        content = override_path.read_text()

        assert "Generated by treemux" in content
        assert "DO NOT EDIT" in content

    def test_file_contains_services(
        self, project_root: Path, sample_treemux_config: TreemuxConfig
    ):
        """servicesセクションを含む"""
        write_override_file(project_root, sample_treemux_config)

        override_path = project_root / OVERRIDE_FILE
        content = override_path.read_text()

        assert "services:" in content
        assert "web:" in content
        assert "api:" in content


class TestBuildEnvVars:
    """Tests for build_env_vars function."""

    def test_project_name(self):
        """TREEMUX_PROJECT_NAMEを設定する"""
        env = build_env_vars("my-project", {})
        assert env["TREEMUX_PROJECT_NAME"] == "my-project"

    def test_port_env_vars(self):
        """各サービスにTREEMUX_{SERVICE}_PORTを設定する"""
        env = build_env_vars("project", {"web": 8001, "api": 8101})

        assert env["TREEMUX_WEB_PORT"] == "8001"
        assert env["TREEMUX_API_PORT"] == "8101"

    def test_uppercase_conversion(self):
        """サービス名は大文字化され、ハイフンはアンダースコアに変換される"""
        env = build_env_vars("project", {"my-service": 9000})
        assert "TREEMUX_MY_SERVICE_PORT" in env

    def test_empty_ports(self):
        """空のports dictで動作する"""
        env = build_env_vars("project", {})
        assert env == {"TREEMUX_PROJECT_NAME": "project"}


class TestComposeUp:
    """Tests for compose_up function."""

    @patch("treemux.compose.subprocess.run")
    def test_command_structure(self, mock_run, project_root: Path):
        """正しいdocker composeコマンドを構築する"""
        mock_run.return_value = MagicMock(returncode=0, stdout="", stderr="")

        compose_up(
            project_root,
            project_name="test-project",
            env_vars={"TREEMUX_PROJECT_NAME": "test"},
        )

        call_args = mock_run.call_args
        cmd = call_args[0][0]

        assert cmd[:2] == ["docker", "compose"]
        assert "--project-name" in cmd
        assert "test-project" in cmd
        assert "-f" in cmd
        assert "docker-compose.yml" in cmd
        assert OVERRIDE_FILE in cmd
        assert "up" in cmd
        assert "-d" in cmd  # detach by default

    @patch("treemux.compose.subprocess.run")
    def test_detach_false(self, mock_run, project_root: Path):
        """detach=Falseの場合は-dを含まない"""
        mock_run.return_value = MagicMock(returncode=0, stdout="", stderr="")

        compose_up(project_root, "proj", {}, detach=False)

        cmd = mock_run.call_args[0][0]
        assert "-d" not in cmd

    @patch("treemux.compose.subprocess.run")
    def test_success_result(self, mock_run, project_root: Path):
        """returncode=0で成功結果を返す"""
        mock_run.return_value = MagicMock(returncode=0, stdout="Created", stderr="")

        result = compose_up(project_root, "proj", {})

        assert result.success is True
        assert result.return_code == 0
        assert result.stdout == "Created"

    @patch("treemux.compose.subprocess.run")
    def test_failure_result(self, mock_run, project_root: Path):
        """非ゼロのreturncodeで失敗結果を返す"""
        mock_run.return_value = MagicMock(returncode=1, stdout="", stderr="Error")

        result = compose_up(project_root, "proj", {})

        assert result.success is False
        assert result.return_code == 1
        assert result.stderr == "Error"


class TestComposeDown:
    """Tests for compose_down function."""

    @patch("treemux.compose.subprocess.run")
    def test_basic_command(self, mock_run, project_root: Path):
        """正しいdownコマンドを構築する"""
        mock_run.return_value = MagicMock(returncode=0, stdout="", stderr="")

        compose_down(project_root, "test-project")

        cmd = mock_run.call_args[0][0]
        assert "down" in cmd
        assert "-v" not in cmd

    @patch("treemux.compose.subprocess.run")
    def test_with_volumes(self, mock_run, project_root: Path):
        """volumes=Trueの場合は-vを含む"""
        mock_run.return_value = MagicMock(returncode=0, stdout="", stderr="")

        compose_down(project_root, "test-project", volumes=True)

        cmd = mock_run.call_args[0][0]
        assert "-v" in cmd


class TestComposePs:
    """Tests for compose_ps function."""

    @patch("treemux.compose.subprocess.run")
    def test_json_format(self, mock_run, project_root: Path):
        """--format jsonを含む"""
        mock_run.return_value = MagicMock(returncode=0, stdout="[]", stderr="")

        compose_ps(project_root, "test-project")

        cmd = mock_run.call_args[0][0]
        assert "--format" in cmd
        assert "json" in cmd


class TestCheckDockerComposeAvailable:
    """Tests for check_docker_compose_available function."""

    @patch("treemux.compose.subprocess.run")
    def test_available(self, mock_run):
        """docker composeが利用可能な場合はTrueを返す"""
        mock_run.return_value = MagicMock(returncode=0)

        assert check_docker_compose_available() is True

        cmd = mock_run.call_args[0][0]
        assert cmd == ["docker", "compose", "version"]

    @patch("treemux.compose.subprocess.run")
    def test_not_available(self, mock_run):
        """コマンドが失敗した場合はFalseを返す"""
        mock_run.return_value = MagicMock(returncode=1)

        assert check_docker_compose_available() is False

    @patch("treemux.compose.subprocess.run")
    def test_not_found(self, mock_run):
        """dockerが見つからない場合はFalseを返す"""
        mock_run.side_effect = FileNotFoundError()

        assert check_docker_compose_available() is False


class TestOverrideFileHelpers:
    """Tests for override file helper functions."""

    def test_get_override_file_path(self, project_root: Path):
        """正しいパスを返す"""
        result = get_override_file_path(project_root)
        assert result == project_root / OVERRIDE_FILE

    def test_override_file_exists_true(
        self, project_root: Path, sample_treemux_config: TreemuxConfig
    ):
        """ファイルが存在する場合はTrueを返す"""
        write_override_file(project_root, sample_treemux_config)
        assert override_file_exists(project_root) is True

    def test_override_file_exists_false(self, project_root: Path):
        """ファイルが存在しない場合はFalseを返す"""
        assert override_file_exists(project_root) is False
